"""Quant API 33 因子精编元数据。

每条记录为产品级因子元数据，字段对齐《A股因子数据库产品交付方案》
(docs/FACTOR_DB_DELIVERY_PLAN.md) 第 2.2 节的元数据规范。

数据来源：Quant API v2 factor_monthly 表（月频，约 5,400 只全A 股票，
2020-01-23 起）。formula_expr 与
research_core/factor_lab/libraries/quant_api_33/specs.py 保持一致。
"""

from __future__ import annotations

DATA_SOURCE = "Quant API v2 factor_monthly（RQData 月频因子表）"
FREQUENCY = "月频"
COVERAGE = "全A 约5,400只（自然剔除停牌/无交易月份）"
HISTORY_START = "2020-01-23"

_SOURCE_FIELDS_NOTE = "输入字段均来自 Quant API：财务字段取自财务三表（PIT 口径），行情字段取自后复权日 K。"


def _meta(
    *,
    name: str,
    name_cn: str,
    name_en: str,
    category: str,
    subcategory: str,
    formula_expr: str,
    formula_latex: str,
    definition: str,
    calc_logic: str,
    logic_notes: str,
    application: str,
    cautions: str,
) -> dict:
    return {
        "factor_id": f"QAPI33:{name}",
        "name_cn": name_cn,
        "name_en": name_en,
        "category": category,
        "subcategory": subcategory,
        "data_source": DATA_SOURCE,
        "frequency": FREQUENCY,
        "coverage": COVERAGE,
        "history_start": HISTORY_START,
        "definition": definition,
        "calc_logic": calc_logic,
        "formula_expr": formula_expr,
        "formula_latex": formula_latex,
        "logic_notes": logic_notes,
        "application": application,
        "cautions": cautions,
    }


QUANT_API_33_META: list[dict] = [
    # ============ 基础因子（价格/成交/流动性） ============
    _meta(
        name="log_price",
        name_cn="对数价格",
        name_en="Log Price",
        category="基础因子",
        subcategory="价格",
        formula_expr="log(close)",
        formula_latex=r"P^{\log}_{t} = \ln P_{t}",
        definition="股票后复权收盘价的自然对数，刻画价格水平的量级。",
        calc_logic="月末取后复权收盘价，取自然对数得到月频截面值。",
        logic_notes="对数变换压缩价格的数量级差异，使高价股与低价股在横截面上可比。" + _SOURCE_FIELDS_NOTE,
        application="规模/价格风格暴露分析、小市值效应研究、作为控制变量进入多因子回归。",
        cautions="必须使用后复权价格，否则分红除权会产生虚假跳变；新股上市初期价格不稳定。",
    ),
    _meta(
        name="avg_amount_1m",
        name_cn="月均成交额",
        name_en="1-Month Average Turnover Amount",
        category="基础因子",
        subcategory="流动性",
        formula_expr="mean(amount, 21)",
        formula_latex=r"\bar{A}_{21,t} = \frac{1}{21}\sum_{i=0}^{20} A_{t-i}",
        definition="过去 21 个交易日（约 1 个月）日成交额的均值，衡量交易活跃度与流动性规模。",
        calc_logic="按日频成交额滚动 21 日求均值，月末取截面值。",
        logic_notes="成交额同时包含价格与成交量信息，是流动性的一级代理变量。",
        application="流动性风格分类、组合容量测算（策略资金规模上限评估）、异常成交监控。",
        cautions="单位为元，横截面呈长右尾分布，直接使用建议取对数；指数成分调整前后成交额会有结构性跳变。",
    ),
    _meta(
        name="log_amount_1m",
        name_cn="对数成交额",
        name_en="Log Average Turnover Amount",
        category="基础因子",
        subcategory="流动性",
        formula_expr="log(avg_amount_1m)",
        formula_latex=r"A^{\log}_{t} = \ln\!\left(\bar{A}_{21,t}\right)",
        definition="月均成交额的自然对数，将长尾分布的成交额转换为近似正态的横截面分布。",
        calc_logic="先计算 21 日均成交额，再取自然对数。",
        logic_notes="对数变换后截面分布接近对称，便于 z-score 标准化与回归使用。",
        application="流动性因子构建（如非流动性因子的分母）、流动性中性化预处理。",
        cautions="成交额为零（长期停牌）时对数无定义，实现中以缺失值处理。",
    ),
    _meta(
        name="turnover_proxy",
        name_cn="换手率代理",
        name_en="Turnover Proxy",
        category="基础因子",
        subcategory="流动性",
        formula_expr="volume / mean(volume, 252)",
        formula_latex=r"T_{t} = \frac{V_{t}}{\frac{1}{252}\sum_{i=0}^{251} V_{t-i}}",
        definition="当日成交量相对过去一年平均成交量的比值，代理异常换手热度。",
        calc_logic="月末当日成交量除以 252 日均量。",
        logic_notes="以自身历史为基准做标准化，剔除了个股间成交量量级的差异，捕捉相对活跃度变化。",
        application="情绪过热识别、事件驱动交易中的关注度确认、异常量能监控。",
        cautions="上市不满一年的股票 252 日均量样本不足，值偏大；大宗交易日会显著抬升该值。",
    ),
    _meta(
        name="volume_ratio",
        name_cn="量比（5日/21日）",
        name_en="Volume Ratio (5d/21d)",
        category="基础因子",
        subcategory="流动性",
        formula_expr="mean(volume, 5) / mean(volume, 21)",
        formula_latex=r"VR_{t} = \frac{\bar{V}_{5,t}}{\bar{V}_{21,t}}",
        definition="近 5 日平均成交量与近 21 日平均成交量之比，衡量短期量能变化方向。",
        calc_logic="分别计算 5 日与 21 日均量后取比值，月末取截面值。",
        logic_notes="比值>1 表示近期放量，<1 表示缩量；是对量能趋势的短窗口刻画。",
        application="量价配合分析（放量上涨/缩量下跌形态识别）、短期资金流向跟踪。",
        cautions="停牌复牌后短期均量剧烈波动，比值失真；建议与换手率代理配合使用。",
    ),
    _meta(
        name="illiquidity",
        name_cn="Amihud 非流动性",
        name_en="Amihud Illiquidity",
        category="基础因子",
        subcategory="流动性",
        formula_expr="mean(abs(daily_return) / amount, 21)",
        formula_latex=r"ILLIQ_{t} = \frac{1}{21}\sum_{i=0}^{20} \frac{|r_{t-i}|}{A_{t-i}}",
        definition="Amihud (2002) 非流动性指标：单位成交额引起的价格变动，衡量价格冲击成本。",
        calc_logic="逐日计算 |日收益|/成交额，再取 21 日均值，月末取截面值。",
        logic_notes="值越大表示推动价格所需资金越少、流动性越差；是流动性风险定价的经典代理。",
        application="流动性溢价研究、交易成本预估、流动性风险因子暴露控制。",
        cautions="数值量级极小（约 1e-9），使用前需乘以 1e9 或取对数；成交额极端小的日子会主导均值。",
    ),
    # ============ 技术因子（动量/反转） ============
    _meta(
        name="ret_1m",
        name_cn="1月收益率（短动量）",
        name_en="1-Month Return",
        category="技术因子",
        subcategory="动量",
        formula_expr="close / delay(close, 21) - 1",
        formula_latex=r"R_{1m,t} = \frac{P_{t}}{P_{t-21}} - 1",
        definition="过去 21 个交易日的区间收益率。",
        calc_logic="月末后复权收盘价除以 21 个交易日前的收盘价再减一。",
        logic_notes="A股短周期呈显著反转效应，1 月收益在截面上与未来收益多为负相关。",
        application="短期反转策略核心因子、动量/反转风格切换研究。",
        cautions="涨停/跌停股票价格不可交易，回测需加涨跌停约束；次新股波动剧烈。",
    ),
    _meta(
        name="ret_3m",
        name_cn="3月收益率",
        name_en="3-Month Return",
        category="技术因子",
        subcategory="动量",
        formula_expr="close / delay(close, 63) - 1",
        formula_latex=r"R_{3m,t} = \frac{P_{t}}{P_{t-63}} - 1",
        definition="过去 63 个交易日（约一季度）的区间收益率。",
        calc_logic="月末收盘价相对 63 日前收盘价的涨跌幅。",
        logic_notes="3 月窗口处于 A 股动量与反转的过渡区，效应不稳定，常与其他窗口组合使用。",
        application="多窗口动量组合、行业轮动信号。",
        cautions="单窗口动量在 A 股的 IC 符号历史上多次翻转，建议结合波动率调整（见 ret_3m_vol_adj）。",
    ),
    _meta(
        name="ret_6m",
        name_cn="6月收益率",
        name_en="6-Month Return",
        category="技术因子",
        subcategory="动量",
        formula_expr="close / delay(close, 126) - 1",
        formula_latex=r"R_{6m,t} = \frac{P_{t}}{P_{t-126}} - 1",
        definition="过去 126 个交易日（约半年）的区间收益率。",
        calc_logic="月末收盘价相对 126 日前收盘价的涨跌幅。",
        logic_notes="半年窗口开始呈现中期动量特征，但 A 股仍以反转为主导。",
        application="中期动量验证、与 12 月动量组合构建动量期限结构。",
        cautions="跨越报告期时会混入基本面信息变化，纯价格解释力下降。",
    ),
    _meta(
        name="ret_12m",
        name_cn="12月收益率",
        name_en="12-Month Return",
        category="技术因子",
        subcategory="动量",
        formula_expr="close / delay(close, 252) - 1",
        formula_latex=r"R_{12m,t} = \frac{P_{t}}{P_{t-252}} - 1",
        definition="过去 252 个交易日（约一年）的区间收益率。",
        calc_logic="月末收盘价相对一年前收盘价的涨跌幅。",
        logic_notes="经典动量研究（Jegadeesh & Titman 1993）的基准窗口；A 股 12 月收益反转效应弱于美股。",
        application="经典动量策略（配合 momentum_12_1 剔除近月）、年度相对强弱排序。",
        cautions="须剔除上市不满一年的样本；跨牛熊周期的 12 月收益含大量 beta 暴露。",
    ),
    _meta(
        name="momentum_12_1",
        name_cn="12-1 动量（剔除近月）",
        name_en="12-1 Momentum (Skip Month)",
        category="技术因子",
        subcategory="动量",
        formula_expr="delay(close, 21) / delay(close, 252) - 1",
        formula_latex=r"M_{12\text{-}1,t} = \frac{P_{t-21}}{P_{t-252}} - 1",
        definition="经典学术动量定义：t-21 日至 t-252 日的收益率，即 12 个月动量剔除最近 1 个月。",
        calc_logic="21 个交易日前的收盘价除以 252 个交易日前的收盘价再减一。",
        logic_notes="剔除近月是为了规避短期反转与涨跌停、并购等微观结构噪音，学术文献标准做法。",
        application="动量策略标准因子、行为金融（反应不足）实证研究。",
        cautions="A 股动量效应弱且不稳定，历史上多呈现动量崩溃（momentum crash）特征。",
    ),
    _meta(
        name="reversal",
        name_cn="1月反转",
        name_en="1-Month Reversal",
        category="技术因子",
        subcategory="反转",
        formula_expr="-ret_1m",
        formula_latex=r"REV_{t} = -R_{1m,t}",
        definition="1 月收益率的相反数，A 股最强的异象之一：短期超跌的股票未来倾向于反弹。",
        calc_logic="对 1 月收益率取负号。",
        logic_notes="反转因子在 A 股月频截面上长期 IC 为正（即与未来收益正相关），源于过度反应修正。",
        application="短期反转策略、与流动性因子组合（反转在小盘高换手股中最强）。",
        cautions="反转策略换手率极高、对交易成本敏感；跌停无法买入会导致理论收益不可实现。",
    ),
    # ============ 技术因子（波动率） ============
    _meta(
        name="volatility_1m",
        name_cn="1月波动率",
        name_en="1-Month Volatility",
        category="技术因子",
        subcategory="波动率",
        formula_expr="stddev(daily_return, 21)",
        formula_latex=r"\sigma_{21,t} = \sqrt{\frac{1}{20}\sum_{i=0}^{20}\left(r_{t-i} - \bar{r}_{21,t}\right)^{2}}",
        definition="过去 21 个交易日日收益率的标准差，衡量短期价格波动水平。",
        calc_logic="对日收益率做 21 日滚动标准差，月末取截面值。",
        logic_notes="低波动异象（low-vol anomaly）：低波动股票风险调整后收益长期优于高波动股票。",
        application="低波动策略、风险控制过滤（剔除高波动股）、波动率风格暴露分析。",
        cautions="高波动与彩票偏好、壳价值等混杂；建议对数化或 rank 处理后使用。",
    ),
    _meta(
        name="volatility_3m",
        name_cn="3月波动率",
        name_en="3-Month Volatility",
        category="技术因子",
        subcategory="波动率",
        formula_expr="stddev(daily_return, 63)",
        formula_latex=r"\sigma_{63,t} = \sqrt{\frac{1}{62}\sum_{i=0}^{62}\left(r_{t-i} - \bar{r}_{63,t}\right)^{2}}",
        definition="过去 63 个交易日日收益率的标准差，中期波动水平。",
        calc_logic="对日收益率做 63 日滚动标准差。",
        logic_notes="3 月窗口对单日异常波动的敏感度低于 1 月窗口，更稳健。",
        application="中期风险筛选、波动率期限结构分析（配合 1m/6m）。",
        cautions="财报季（4月/8月/10月）波动率系统性抬升，存在季节性。",
    ),
    _meta(
        name="volatility_6m",
        name_cn="6月波动率",
        name_en="6-Month Volatility",
        category="技术因子",
        subcategory="波动率",
        formula_expr="stddev(daily_return, 126)",
        formula_latex=r"\sigma_{126,t} = \sqrt{\frac{1}{125}\sum_{i=0}^{125}\left(r_{t-i} - \bar{r}_{126,t}\right)^{2}}",
        definition="过去 126 个交易日日收益率的标准差，长期波动水平。",
        calc_logic="对日收益率做 126 日滚动标准差。",
        logic_notes="长窗口波动率近似个股的系统性风险水平，与市值、流动性因子相关性较高。",
        application="风险模型（Barra 式残差波动率的基础）、长周期风险预算。",
        cautions="窗口越长对新信息的反应越慢；与 beta 因子存在共线性。",
    ),
    _meta(
        name="vol_convergence",
        name_cn="波动率收敛比",
        name_en="Volatility Convergence Ratio",
        category="技术因子",
        subcategory="波动率",
        formula_expr="volatility_1m / volatility_3m",
        formula_latex=r"VC_{t} = \frac{\sigma_{21,t}}{\sigma_{63,t}}",
        definition="短期波动率与中期波动率之比，捕捉波动率状态的变化方向。",
        calc_logic="1 月波动率除以 3 月波动率。",
        logic_notes="比值<1 表示波动率收敛（市场趋于平静），>1 表示波动率发散；波动率具有均值回复特征。",
        application="波动率状态识别、风险择时辅助信号。",
        cautions="比值无量纲但分布右偏；3 月波动率接近零的样本会产生极端值。",
    ),
    _meta(
        name="max_ret_1m",
        name_cn="1月最大单日收益（彩票偏好）",
        name_en="1-Month Maximum Daily Return",
        category="技术因子",
        subcategory="波动率",
        formula_expr="max(daily_return, 21)",
        formula_latex=r"R^{\max}_{21,t} = \max_{0 \le i \le 20}\; r_{t-i}",
        definition="过去 21 个交易日内单日收益率的最大值。",
        calc_logic="对日收益率做 21 日滚动最大值。",
        logic_notes="MAX 效应（Bali et al. 2011）：极端单日大涨的股票具有彩票特征，未来收益显著为负。",
        application="彩票偏好异象策略、剔除博彩型股票的负面清单。",
        cautions="涨停板的收益率上限影响分布；次新股与题材股该值极端，需结合上市时长过滤。",
    ),
    _meta(
        name="min_ret_1m",
        name_cn="1月最小单日收益",
        name_en="1-Month Minimum Daily Return",
        category="技术因子",
        subcategory="波动率",
        formula_expr="min(daily_return, 21)",
        formula_latex=r"R^{\min}_{21,t} = \min_{0 \le i \le 20}\; r_{t-i}",
        definition="过去 21 个交易日内单日收益率的最小值。",
        calc_logic="对日收益率做 21 日滚动最小值。",
        logic_notes="极端单日大跌刻画尾部风险与强制平仓压力，与 max_ret 构成偏度信息的两端。",
        application="尾部风险监控、崩盘风险预警、偏度因子构建素材。",
        cautions="跌停无法卖出，该值隐含的流动性风险在组合中不易对冲。",
    ),
    _meta(
        name="up_ratio_1m",
        name_cn="1月上涨天数占比",
        name_en="1-Month Up-Day Ratio",
        category="技术因子",
        subcategory="波动率",
        formula_expr="mean(daily_return > 0, 21)",
        formula_latex=r"UP_{t} = \frac{1}{21}\sum_{i=0}^{20} \mathbb{1}\{r_{t-i} > 0\}",
        definition="过去 21 个交易日中上涨天数的占比，值域 [0,1]。",
        calc_logic="对「日收益>0」的布尔值做 21 日均值。",
        logic_notes="信息离散度视角：持续小阳线的股票比单日暴涨的股票信息环境更平滑。",
        application="替代动量的稳健信号、与 max_ret 组合刻画上涨质量。",
        cautions="平盘日不计入上涨；小幅度上涨的占比高不代表累计收益高。",
    ),
    _meta(
        name="high_low_1m",
        name_cn="1月振幅",
        name_en="1-Month High-Low Range",
        category="技术因子",
        subcategory="波动率",
        formula_expr="max(high, 21) / min(low, 21) - 1",
        formula_latex=r"HL_{t} = \frac{\max_{0 \le i \le 20} H_{t-i}}{\min_{0 \le i \le 20} L_{t-i}} - 1",
        definition="过去 21 日最高价与最低价之比减一，价格通道宽度。",
        calc_logic="21 日滚动最高价除以 21 日滚动最低价再减一。",
        logic_notes="由价格极值（而非收益率）定义的波动度量，对单日跳空不敏感，捕捉区间宽度。",
        application="通道突破策略的通道宽度基准、波动风格分类。",
        cautions="使用未复权高低价时除权会产生虚假极值；一字涨跌停板期间通道持续收窄。",
    ),
    _meta(
        name="amplitude_1m",
        name_cn="1月日均振幅",
        name_en="1-Month Average Daily Amplitude",
        category="技术因子",
        subcategory="波动率",
        formula_expr="mean((high - low) / close, 21)",
        formula_latex=r"AMP_{t} = \frac{1}{21}\sum_{i=0}^{20} \frac{H_{t-i} - L_{t-i}}{C_{t-i}}",
        definition="过去 21 日日内振幅（高低价差/收盘价）的均值，刻画日内多空分歧强度。",
        calc_logic="逐日计算 (high-low)/close，再取 21 日均值。",
        logic_notes="日内振幅反映盘中多空博弈的分歧，高振幅股票往往伴随高换手与高投机性。",
        application="投机情绪监控、与换手率组合识别题材炒作股。",
        cautions="集合竞价与盘中瞬时打针（乌龙指）会污染极值；A股 T+1 制度下振幅信息与美股含义不同。",
    ),
    _meta(
        name="ret_3m_vol_adj",
        name_cn="波动率调整动量",
        name_en="Volatility-Adjusted 3-Month Momentum",
        category="技术因子",
        subcategory="动量",
        formula_expr="ret_3m / volatility_3m",
        formula_latex=r"M^{va}_{t} = \frac{R_{3m,t}}{\sigma_{63,t}}",
        definition="3 月收益率除以 3 月波动率，即收益的夏普式标准化（信息比率形态的动量）。",
        calc_logic="先分别计算 3 月收益与 3 月波动率，再做除法。",
        logic_notes="用波动率做分母对动量做风险调整，缓解高波动股主导动量组合的问题（Frog-in-the-Pan 的稳健变体）。",
        application="稳健动量策略、多因子模型中替代原始动量以降低组合波动。",
        cautions="波动率极小的股票（长期横盘）会产生极端值，需对分母加下限保护。",
    ),
    # ============ 技术因子（技术指标） ============
    _meta(
        name="rsi_14",
        name_cn="14日相对强弱指标（RSI）",
        name_en="14-Day Relative Strength Index",
        category="技术因子",
        subcategory="技术指标",
        formula_expr="100 - 100 / (1 + mean(up_move, 14) / mean(down_move, 14))",
        formula_latex=r"RSI_{14,t} = 100 - \frac{100}{1 + \dfrac{\frac{1}{14}\sum U_{t-i}}{\frac{1}{14}\sum D_{t-i}}}",
        definition="Wilder 相对强弱指标：上涨动量与下跌动量之比的归一化表达，值域 [0,100]。",
        calc_logic="以 14 日平均上涨幅度 U 与平均下跌幅度 D 之比计算，月末取截面值。",
        logic_notes="RSI>70 传统上视为超买、<30 视为超卖；截面使用时更关注其相对排序而非绝对阈值。",
        application="超买超卖筛选、与技术形态组合的择时信号。",
        cautions="单边趋势行情中 RSI 长期钝化；不同软件对均值（SMA/Wilder EMA）口径不同，跨源比对需确认。",
    ),
    _meta(
        name="bb_position",
        name_cn="布林带位置",
        name_en="Bollinger Band Position",
        category="技术因子",
        subcategory="技术指标",
        formula_expr="(close - bollinger_lower_20_2) / (bollinger_upper_20_2 - bollinger_lower_20_2)",
        formula_latex=r"BB_{t} = \frac{C_{t} - \mu_{20,t} + 2\sigma_{20,t}}{4\sigma_{20,t}}",
        definition="收盘价在 20 日均值±2倍标准差布林带通道中的相对位置，值域通常 [0,1]。",
        calc_logic="收盘价减下轨除以通道宽度，其中上下轨为 20 日均值加减 2 倍标准差。",
        logic_notes="位置接近 0 表示触及下轨（超卖），接近 1 表示触及上轨（超买）；是价格相对自身通道的标准化。",
        application="均值回复策略入场点识别、突破形态确认。",
        cautions="波动率骤缩时通道极窄，位置指标剧烈抖动；强趋势中沿上轨运行不构成卖出信号。",
    ),
    _meta(
        name="ma_signal",
        name_cn="均线偏离信号",
        name_en="Moving Average Deviation Signal",
        category="技术因子",
        subcategory="技术指标",
        formula_expr="close / mean(close, 20) - 1",
        formula_latex=r"MA_{t} = \frac{C_{t}}{\bar{C}_{20,t}} - 1",
        definition="收盘价相对 20 日均线的偏离率，衡量短期价格与中期趋势的乖离程度。",
        calc_logic="收盘价除以 20 日均价再减一。",
        logic_notes="正偏离表示价格站上均线，负偏离表示跌破；乖离率过大时存在均值回复引力。",
        application="趋势跟随确认、乖离率反转策略（极端偏离时反向）。",
        cautions="均线窗口选择敏感（20/60/120 差异大）；横盘市中信号频繁翻转。",
    ),
    # ============ 基本面因子（盈利） ============
    _meta(
        name="roe_ttm",
        name_cn="净资产收益率（TTM）",
        name_en="Return on Equity (TTM)",
        category="基本面因子",
        subcategory="盈利能力",
        formula_expr="net_profit_ttm / equity",
        formula_latex=r"ROE_{ttm,t} = \frac{NP_{ttm,t}}{E_{t}}",
        definition="滚动十二个月归母净利润与归属股东权益之比，衡量股东资本的盈利效率。",
        calc_logic="分子为最近四个季度归母净利润之和，分母为最新报告期归属母公司股东权益。",
        logic_notes="巴菲特最重视的单一指标：高且稳定的 ROE 是复利能力的直接体现。" + _SOURCE_FIELDS_NOTE,
        application="质量风格选股核心因子、多因子模型质量维度、PB-ROE 框架。",
        cautions="金融/地产等高杠杆行业 ROE 系统性偏高，跨行业比较需中性化；分红导致净资产下降会推高 ROE。",
    ),
    _meta(
        name="roa_ttm",
        name_cn="总资产收益率（TTM）",
        name_en="Return on Assets (TTM)",
        category="基本面因子",
        subcategory="盈利能力",
        formula_expr="net_profit_ttm / assets",
        formula_latex=r"ROA_{ttm,t} = \frac{NP_{ttm,t}}{A_{t}}",
        definition="滚动十二个月归母净利润与总资产之比，衡量全部资产的使用效率。",
        calc_logic="分子为 TTM 归母净利润，分母为最新报告期总资产。",
        logic_notes="相比 ROE 剔除了杠杆放大效应，更适合跨杠杆水平比较盈利质量。",
        application="盈利质量筛选（高 ROA+低杠杆组合）、规避高杠杆虚假繁荣。",
        cautions="重资产行业（银行/公用事业）ROA 天然偏低；总资产含商誉时需关注减值风险。",
    ),
    _meta(
        name="net_margin",
        name_cn="销售净利率（TTM）",
        name_en="Net Profit Margin (TTM)",
        category="基本面因子",
        subcategory="盈利能力",
        formula_expr="net_profit_ttm / revenue_ttm",
        formula_latex=r"NPM_{ttm,t} = \frac{NP_{ttm,t}}{REV_{ttm,t}}",
        definition="TTM 归母净利润与 TTM 营业收入之比，衡量每单位收入的利润留存。",
        calc_logic="分子分母均为滚动十二个月口径。",
        logic_notes="净利率是杜邦分解中 ROE 的第一层驱动，反映定价权与成本控制能力。",
        application="盈利能力拆解（杜邦分析）、定价权强的消费/医药股筛选。",
        cautions="非经常性损益（资产处置、政府补助）会污染净利率；周期股景气顶部净利率不可持续。",
    ),
    # ============ 基本面因子（成长） ============
    _meta(
        name="revenue_yoy",
        name_cn="营业收入同比增长率",
        name_en="Revenue Growth (YoY)",
        category="基本面因子",
        subcategory="成长性",
        formula_expr="revenue_yoy",
        formula_latex=r"g^{REV}_{t} = \frac{REV_{t} - REV_{t-4Q}}{REV_{t-4Q}}",
        definition="最新报告期营业收入相对上年同期营业收入的增长率。",
        calc_logic="取财报披露的营业收入同比增速字段（PIT 口径）。",
        logic_notes="收入成长是利润成长的先行指标；收入与利润增速的背离（剪刀差）常预示拐点。",
        application="成长风格选股、景气度跟踪、收入-利润增速匹配度分析。",
        cautions="并购并表会制造虚假内生增长；低基数效应导致同比虚高；PIT 口径下需防范财报修订。",
    ),
    _meta(
        name="profit_yoy",
        name_cn="净利润同比增长率",
        name_en="Net Profit Growth (YoY)",
        category="基本面因子",
        subcategory="成长性",
        formula_expr="profit_yoy",
        formula_latex=r"g^{NP}_{t} = \frac{NP_{t} - NP_{t-4Q}}{NP_{t-4Q}}",
        definition="最新报告期归母净利润相对上年同期的增长率。",
        calc_logic="取财报披露的净利润同比增速字段（PIT 口径）。",
        logic_notes="利润成长直接驱动估值切换，但波动远大于收入成长，稳定性差。",
        application="成长股核心因子、业绩驱动的事件窗口（财报季）策略。",
        cautions="基数效应极强（去年微利/亏损时增速为千倍级）；建议结合 SUE（标准化预期外盈利）使用。",
    ),
    _meta(
        name="eps_yoy",
        name_cn="每股收益同比增长率",
        name_en="EPS Growth (YoY)",
        category="基本面因子",
        subcategory="成长性",
        formula_expr="eps_yoy",
        formula_latex=r"g^{EPS}_{t} = \frac{EPS_{t} - EPS_{t-4Q}}{EPS_{t-4Q}}",
        definition="最新报告期每股收益相对上年同期的增长率。",
        calc_logic="取财报披露的 EPS 同比增速字段（PIT 口径）。",
        logic_notes="EPS 增速已剔除股本变动影响（相对净利润增速），更贴近股东视角的每股盈利成长。",
        application="成长因子构建、与净利润增速交叉验证识别摊薄效应。",
        cautions="送转股导致的 EPS 机械调整已在同比口径内消化，但增发摊薄需单独关注。",
    ),
    # ============ 基本面因子（杠杆/运营） ============
    _meta(
        name="debt_to_asset",
        name_cn="资产负债率",
        name_en="Debt-to-Asset Ratio",
        category="基本面因子",
        subcategory="杠杆水平",
        formula_expr="liabilities / assets",
        formula_latex=r"LEV_{t} = \frac{L_{t}}{A_{t}}",
        definition="总负债与总资产之比，衡量财务杠杆水平与偿债压力。",
        calc_logic="最新报告期总负债除以总资产。",
        logic_notes="杠杆是 ROE 的放大器也是风险源；低杠杆在高利率环境下提供安全边际。",
        application="财务风险过滤（剔除高杠杆股）、质量+安全边际组合构建。",
        cautions="行业差异极大（银行~92%、地产~80%、消费~30%），必须行业内标准化；预收账款（合同负债）是良性负债。",
    ),
    _meta(
        name="asset_turnover",
        name_cn="总资产周转率（TTM）",
        name_en="Asset Turnover (TTM)",
        category="基本面因子",
        subcategory="运营效率",
        formula_expr="revenue_ttm / assets",
        formula_latex=r"AT_{ttm,t} = \frac{REV_{ttm,t}}{A_{t}}",
        definition="TTM 营业收入与总资产之比，衡量资产的运营效率。",
        calc_logic="分子为滚动十二个月营业收入，分母为最新报告期总资产。",
        logic_notes="杜邦分解 ROE 的第二层驱动：周转率刻画商业模式（薄利多销 vs 厚利慢销）。",
        application="杜邦分析全链路（净利率×周转率×杠杆）、运营效率改善型选股。",
        cautions="零售/贸易行业周转率天然高；在建工程转固前会暂时压低周转率。",
    ),
]
